### PR TITLE
List pages that come empty from connection should be marked as ready

### PR DESCRIPTION
**Pull request by orballo**
fixes https://github.com/frontity/wp-org-connection/issues/2

### CODE REVIEW

**Comment by luisherranz** [comment]
I think it's better to assign the reviewer once WIP is removed. That way I don't get a notification until then.

**Comment by orballo** [comment]
The WIP plugin won't remove the WIP state even when the WIP tag is removed from the title. Maybe we should uninstall it and trust the tag in the title.

**Comment by orballo** [comment]
@luisherranz ready for review.

**Comment by luisherranz** [comment]
> The WIP plugin won't remove the WIP state even when the WIP tag is removed from the title. Maybe we should uninstall it and trust the tag in the title.

Hmm... shit.

**Review by luisherranz — APPROVED** [review]
👍 finally

**Pull request merged**
